"""extend bookings: pax, payment, arrival, guest customer, partial unique index

Revision ID: 3a08fcc6b403
Revises: b449960dd99d
Create Date: 2026-09-03 21:42:12.686496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a08fcc6b403'
down_revision: Union[str, Sequence[str], None] = 'b449960dd99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('pax', sa.Integer(), server_default='1', nullable=False))
    op.add_column('bookings', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('downpayment_status', sa.String(), server_default='none', nullable=False))
    op.add_column('bookings', sa.Column('payment_proof_url', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('arrival_time', sa.DateTime(), nullable=True))
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('no_double_booking'), 'bookings', type_='unique')
    op.create_index('ix_active_booking_per_slot', 'bookings', ['service_id', 'slot_start'], unique=True, postgresql_where="status IN ('pending', 'booked')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_active_booking_per_slot', table_name='bookings', postgresql_where="status IN ('pending', 'booked')")
    op.create_unique_constraint(op.f('no_double_booking'), 'bookings', ['service_id', 'slot_start'], postgresql_nulls_not_distinct=False)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bookings', 'arrival_time')
    op.drop_column('bookings', 'payment_proof_url')
    op.drop_column('bookings', 'downpayment_status')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'pax')
    op.drop_column('bookings', 'customer_phone')
    op.drop_column('bookings', 'customer_name')
    # ### end Alembic commands ###
