"""add shop_settings table

Revision ID: fd691dbc44d8
Revises: 3a08fcc6b403
Create Date: 2026-09-04 00:42:54.724549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd691dbc44d8'
down_revision: Union[str, Sequence[str], None] = '3a08fcc6b403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('shop_name', sa.String(), server_default=sa.text("'Kabarbers'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed default row
    op.execute(
        "INSERT INTO shop_settings (id, is_open, shop_name, updated_at) "
        "VALUES (gen_random_uuid(), true, 'Kabarbers', NOW())"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_settings')
    # ### end Alembic commands ###
